### ISSUE TITLE
Error: interface not found in proxy object: org.bluez.GattService1

### ISSUE THREAD

**Issue by lmarschall** [chrvadala/node-ble#38]
So I'm currently trying to get some characteristic values from a device, but unfortunately I can't fix this error. Using bluetoothctl I can easily extract the characteristic values, but with the package things fail.

```
const { bluetooth, destroy } = createBluetooth()
const adapter = await bluetooth.defaultAdapter()

const device = await adapter.waitDevice(uuid);

if(! await device.isConnected()) {

  await device.connect();
}

console.log(await device.isConnected());
await device.gatt();
```

```
throw new Error(`interface not found in proxy object: ${name}`);
            ^

Error: interface not found in proxy object: org.bluez.GattService1
```

**Comment by chrvadala** [comment]
Can you provide your operating system name and version?

**Comment by lmarschall** [comment]
I'm using Ubuntu 22.04. as OS.

**Comment by chrvadala** [comment]
Thanks for the feedback. I added this ubuntu version on the CI pipeline, but I don't see any issue https://github.com/chrvadala/node-ble/pull/39.
Have you tested it on a fresh Ubuntu 2204 installation?

**Comment by lmarschall** [comment]
I'll investigate further in the upcoming days and give some additional information..

**Comment by DhlDeliveryMan** [comment]
I have run into this problem on Ubuntu 22.04 too. Was any resolution found for this issue ?

**Comment by ErfanBahramali** [comment]
any update ?👀
This problem still exists 🚶‍♂️

Error:
```
/home/erfan/Desktop/bluetooth/node_modules/dbus-next/lib/client/proxy-object.js:81
      throw new Error(`interface not found in proxy object: ${name}`);
            ^

Error: interface not found in proxy object: org.bluez.GattService1
    at ProxyObject.getInterface (/home/erfan/Desktop/bluetooth/node_modules/dbus-next/lib/client/proxy-object.js:81:13)
    at BusHelper._prepare (/home/erfan/Desktop/bluetooth/node_modules/node-ble/src/BusHelper.js:32:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BusHelper.prop (/home/erfan/Desktop/bluetooth/node_modules/node-ble/src/BusHelper.js:62:5)
    at async GattServer.init (/home/erfan/Desktop/bluetooth/node_modules/node-ble/src/GattServer.js:31:20)
    at async Device.gatt (/home/erfan/Desktop/bluetooth/node_modules/node-ble/src/Device.js:156:5)
    at async /home/erfan/Desktop/bluetooth/main.js:31:24

Node.js v20.9.0
```

**Comment by chrvadala** [comment]
Do you have a way to reproduce it? A test case would be great

**Comment by ErfanBahramali** [comment]
> Do you have a way to reproduce it? A test case would be great

test it on ubuntu 24.04
